### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lopesnuno** [lopesnuno/IHM#4]
Carlos:

- [x]  Routes e página para editar numero de tele
- [x]  Routes e página reservas => página e route para a reserva
- [x]  Back button preto
- [x] Carrinho

Rafa:
 - [x] Página e route de cofirmação de conta
 - [x] Card model => stock e selecionar 
 - [x] Criar funçao para reservas
 - [x] Favoritos

Tarefas:
- [x] Tarefa 1
- [x] Tarefa 2 
- [x] Tarefa 3
